### ISSUE TITLE
Implement ability to set your own background color or font color

### ISSUE THREAD

**Issue by yagarea** [arieldon/castor#1]
I am trying to use castor but my system theme is making text hard to read.
![image](https://user-images.githubusercontent.com/14349169/145099382-7eefbc84-596c-43f0-946a-79bea4977a51.png)

Please add ability to change color of background or font so I do not have to change my color theme.

**Comment by arieldon** [comment]
I think you confused this project with a different Castor on sourcehut, [here](https://sr.ht/~julienxx/Castor/). Both are Gemini clients, but the one I linked is graphical, whereas this one is not.

**Comment by yagarea** [comment]
sorry, my bad
